### ISSUE TITLE
Memory leak when running queries containing JSON columns

### ISSUE THREAD

**Issue by justinpryzby** [PyGreSQL/PyGreSQL#57] opened 2021-01-07 23:51 UTC
PGDATABASE=ts command time -v python3.6 ./cachelike.py 1
...
Maximum resident set size (kbytes): 258908

PGDATABASE=ts command time -v python3.6 ./cachelike.py 11
...
Maximum resident set size (kbytes): 717784

cat ./cachelike.py
```
import pg
import sys

db=pg.DB()

def f():
        return db.query("SELECT * FROM cached_objs WHERE cached_obj_name LIKE 'thresrept.%' ORDER BY 1 DESC").getresult()

for i in range(int(sys.argv[1])):
        f()
```

**Comment by Cito** [comment] 2021-01-08 12:43
Cannot reproduce this using a simple table.

Can you provide a self-contained example, i.e. one that creates a test table and some test data with which this can be reproduced?

Also, which Pygres & Postgres version and which operating system?

**Comment by justinpryzby** [comment] 2021-01-08 17:56
On Fri, Jan 08, 2021 at 04:44:02AM -0800, Christoph Zwerschke wrote:
> Cannot reproduce this using a simple table.
> Can you provide a self-contained example, i.e. one that creates a test table and some test data with which this can be reproduced?
> Also, which Pygres & Postgres version and which operating system?

I reproduced using 5.2.2 under centos7/x86_64.

The issue can be avoided by calling pg.set_jsondecode(None).

Maybe a refcounting issue ?

import pg,sys
db = pg.DB()
#pg.set_jsondecode(None)

db.query('DROP TABLE IF EXISTS leak_')
db.query("CREATE TABLE leak_ AS SELECT '{}'::json FROM generate_series(1,9999)")
for i in range(int(sys.argv[1])):
        db.query("SELECT * FROM leak_").getresult()

**Comment by Cito** [comment] 2021-01-08 21:51
Thanks for providing this reproducible example. As you already guessed, it was a refcounting issue that happened when the query contained JSON, that's why I couldn't reproduce it at first. 

Should be fixed with the latest commit. Can you check if it works for you now with the master branch?

**Comment by justinpryzby** [comment] 2021-01-08 22:10
On Fri, Jan 08, 2021 at 01:51:35PM -0800, Christoph Zwerschke wrote:
> Thanks for providing this reproducible example. As you already guessed, it was a refcounting issue that happened when the query contained JSON, that's why I couldn't reproduce it at first. 
> 
> Should be fixed with the latest commit. Can you check if it works for you now with the master branch?

Seems fixed.  Thanks.

$ PYTHONPATH=./build/lib.linux-x86_64-3.6 PGDATABASE=ts command time -v python3.6 ~/cachelike.py 22
        Maximum resident set size (kbytes): 17144

-- 
Justin

**Closed** 2021-01-08 22:17 UTC
Labels: investigate, question
