### ISSUE TITLE
Classic PyGreSQL API is unaware of generated columns

### ISSUE THREAD

**Issue by seneca-c** [PyGreSQL/PyGreSQL#83] opened 2023-06-16 13:48 UTC
Using generated columns with classic PyGreSQL functions like `insert` or `update` fails unless guard code is written to explicitly remove any references to the generated column from the row dict.  An example of when this has happened is when updating an the tables of an older application that makes heavy use of the classic `get`, `update`, and `insert` combinations to have tsvector columns that are generated in the manner suggested in the PostgreSQL manual.

The value of 's' in pg_attribute.attgenerated indicates these columns that can never be written to.  This is distinct to generated identity columns, which are identified by pg_attribute.attidentity.

**Comment by seneca-c** [comment] 2023-06-16 23:03
I haven't had a chance to get the code to the pr point yet, but here's a sample from what I've been working with on the test side:

    def setUpClass(cls):
        [...]
        try:                                                                                                                                                                                              
            db.query("DROP TABLE _test_generators")                                                                                                                                                       
        except Exception:                                                                                                                                                                                 
            pass                                                                                                                                                                                          
        db.query("CREATE TABLE _test_generators"                                                                                                                                                          
                 " (_always_identity int GENERATED ALWAYS AS IDENTITY, "                                                                                                                                  
                 "  _default_identity int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "                                                                                                                 
                 "  _generated_stored int GENERATED AS (_test + 10) STORED, "                                                                                                                             
                 "  _test int NOT NULL)") 
        [...]

    def test_update_generators(self):                                                                                                                                                                     
        db = open_db()                                                                                                                                                                                    
        db.query("INSERT INTO _test_generators (_test, _default_identity) "                                                                                                                               
                 " VALUES (1234, 1234)")                                                                                                                                                                  
                                                                                                                                                                                                          
        r = db.get('_test_generators', 1234)
        r['_test'] = 4321                                                                                                                                               
        db.update('_test_generators', r)                                                                                                                                                      
        self.assertEqual(r['_test'], 4321)  


This particular case is a bit simplified, but it is effectively what was happening with an application that had a generated tsvector column added to a table to add full text search support.  The non-modifiable "_generated_stored" column in that case was a tsvector of a text column in the table that was only used in SQL queries and indices, and not the python dicts.  db.get() retrieved its value, and including that field, even if not changing it, in an `UPDATE` or any `INSERT` causes PostgreSQL to reject the statement.

**Comment by Cito** [comment] 2023-06-17 19:05
Thanks a lot. I will try to look into it as soon as I find some time to work on PyGreSQL again. Generally, the problem is that PyGreSQL's classic interface is *very* old, it was designed long before things like generated columns existed. But we should still try to make it compatible with databases using such newer features, I agree.

**Comment by Cito** [comment] 2023-08-26 22:22
Fix will be released in version 5.2.5.

**Closed by Cito** 2023-08-26 22:22 UTC
Labels: help wanted
